/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZakatRouteImport } from './routes/zakat'
import { Route as TasbeehRouteImport } from './routes/tasbeeh'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QiblaRouteImport } from './routes/qibla'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrayerTrackerRouteImport } from './routes/prayer-tracker'
import { Route as PrayerTimesRouteImport } from './routes/prayer-times'
import { Route as NamesRouteImport } from './routes/names'
import { Route as MosquesRouteImport } from './routes/mosques'
import { Route as MoreRouteImport } from './routes/more'
import { Route as DuasRouteImport } from './routes/duas'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuranIndexRouteImport } from './routes/quran.index'
import { Route as QuranSurahRouteImport } from './routes/quran.$surah'

const ZakatRoute = ZakatRouteImport.update({
  id: '/zakat',
  path: '/zakat',
  getParentRoute: () => rootRouteImport,
} as any)
const TasbeehRoute = TasbeehRouteImport.update({
  id: '/tasbeeh',
  path: '/tasbeeh',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QiblaRoute = QiblaRouteImport.update({
  id: '/qibla',
  path: '/qibla',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerTrackerRoute = PrayerTrackerRouteImport.update({
  id: '/prayer-tracker',
  path: '/prayer-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerTimesRoute = PrayerTimesRouteImport.update({
  id: '/prayer-times',
  path: '/prayer-times',
  getParentRoute: () => rootRouteImport,
} as any)
const NamesRoute = NamesRouteImport.update({
  id: '/names',
  path: '/names',
  getParentRoute: () => rootRouteImport,
} as any)
const MosquesRoute = MosquesRouteImport.update({
  id: '/mosques',
  path: '/mosques',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const DuasRoute = DuasRouteImport.update({
  id: '/duas',
  path: '/duas',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranIndexRoute = QuranIndexRouteImport.update({
  id: '/quran/',
  path: '/quran/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranSurahRoute = QuranSurahRouteImport.update({
  id: '/quran/$surah',
  path: '/quran/$surah',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/duas': typeof DuasRoute
  '/more': typeof MoreRoute
  '/mosques': typeof MosquesRoute
  '/names': typeof NamesRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/prayer-tracker': typeof PrayerTrackerRoute
  '/profile': typeof ProfileRoute
  '/qibla': typeof QiblaRoute
  '/settings': typeof SettingsRoute
  '/tasbeeh': typeof TasbeehRoute
  '/zakat': typeof ZakatRoute
  '/quran/$surah': typeof QuranSurahRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/duas': typeof DuasRoute
  '/more': typeof MoreRoute
  '/mosques': typeof MosquesRoute
  '/names': typeof NamesRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/prayer-tracker': typeof PrayerTrackerRoute
  '/profile': typeof ProfileRoute
  '/qibla': typeof QiblaRoute
  '/settings': typeof SettingsRoute
  '/tasbeeh': typeof TasbeehRoute
  '/zakat': typeof ZakatRoute
  '/quran/$surah': typeof QuranSurahRoute
  '/quran': typeof QuranIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/duas': typeof DuasRoute
  '/more': typeof MoreRoute
  '/mosques': typeof MosquesRoute
  '/names': typeof NamesRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/prayer-tracker': typeof PrayerTrackerRoute
  '/profile': typeof ProfileRoute
  '/qibla': typeof QiblaRoute
  '/settings': typeof SettingsRoute
  '/tasbeeh': typeof TasbeehRoute
  '/zakat': typeof ZakatRoute
  '/quran/$surah': typeof QuranSurahRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/duas'
    | '/more'
    | '/mosques'
    | '/names'
    | '/prayer-times'
    | '/prayer-tracker'
    | '/profile'
    | '/qibla'
    | '/settings'
    | '/tasbeeh'
    | '/zakat'
    | '/quran/$surah'
    | '/quran/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/duas'
    | '/more'
    | '/mosques'
    | '/names'
    | '/prayer-times'
    | '/prayer-tracker'
    | '/profile'
    | '/qibla'
    | '/settings'
    | '/tasbeeh'
    | '/zakat'
    | '/quran/$surah'
    | '/quran'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar'
    | '/duas'
    | '/more'
    | '/mosques'
    | '/names'
    | '/prayer-times'
    | '/prayer-tracker'
    | '/profile'
    | '/qibla'
    | '/settings'
    | '/tasbeeh'
    | '/zakat'
    | '/quran/$surah'
    | '/quran/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  DuasRoute: typeof DuasRoute
  MoreRoute: typeof MoreRoute
  MosquesRoute: typeof MosquesRoute
  NamesRoute: typeof NamesRoute
  PrayerTimesRoute: typeof PrayerTimesRoute
  PrayerTrackerRoute: typeof PrayerTrackerRoute
  ProfileRoute: typeof ProfileRoute
  QiblaRoute: typeof QiblaRoute
  SettingsRoute: typeof SettingsRoute
  TasbeehRoute: typeof TasbeehRoute
  ZakatRoute: typeof ZakatRoute
  QuranSurahRoute: typeof QuranSurahRoute
  QuranIndexRoute: typeof QuranIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zakat': {
      id: '/zakat'
      path: '/zakat'
      fullPath: '/zakat'
      preLoaderRoute: typeof ZakatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasbeeh': {
      id: '/tasbeeh'
      path: '/tasbeeh'
      fullPath: '/tasbeeh'
      preLoaderRoute: typeof TasbeehRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qibla': {
      id: '/qibla'
      path: '/qibla'
      fullPath: '/qibla'
      preLoaderRoute: typeof QiblaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-tracker': {
      id: '/prayer-tracker'
      path: '/prayer-tracker'
      fullPath: '/prayer-tracker'
      preLoaderRoute: typeof PrayerTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-times': {
      id: '/prayer-times'
      path: '/prayer-times'
      fullPath: '/prayer-times'
      preLoaderRoute: typeof PrayerTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/names': {
      id: '/names'
      path: '/names'
      fullPath: '/names'
      preLoaderRoute: typeof NamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mosques': {
      id: '/mosques'
      path: '/mosques'
      fullPath: '/mosques'
      preLoaderRoute: typeof MosquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duas': {
      id: '/duas'
      path: '/duas'
      fullPath: '/duas'
      preLoaderRoute: typeof DuasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/': {
      id: '/quran/'
      path: '/quran'
      fullPath: '/quran/'
      preLoaderRoute: typeof QuranIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/$surah': {
      id: '/quran/$surah'
      path: '/quran/$surah'
      fullPath: '/quran/$surah'
      preLoaderRoute: typeof QuranSurahRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  DuasRoute: DuasRoute,
  MoreRoute: MoreRoute,
  MosquesRoute: MosquesRoute,
  NamesRoute: NamesRoute,
  PrayerTimesRoute: PrayerTimesRoute,
  PrayerTrackerRoute: PrayerTrackerRoute,
  ProfileRoute: ProfileRoute,
  QiblaRoute: QiblaRoute,
  SettingsRoute: SettingsRoute,
  TasbeehRoute: TasbeehRoute,
  ZakatRoute: ZakatRoute,
  QuranSurahRoute: QuranSurahRoute,
  QuranIndexRoute: QuranIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
